### ISSUE TITLE
名称と訳語の統一について

### ISSUE THREAD

**Issue by kinichiro** [kicad-jp/kicad-gui#1]
名称と訳語を、できるだけ今翻訳中のマニュアルに寄せて統一したいなと考えてます。
マニュアルを読みながら操作する時の違和感を低減できるかと思いまして。
以下のような案を考えてみましたが、いかがでしょうか？
「翻訳での表記」の単語で示しましょう、という意図です。

英語                         |翻訳での表記                            |日本語説明                    |
-----------------------------|----------------------------------------|------------------------------|
KiCad                        |KiCad プロジェクト・マネージャ          |                              |
Eeschema                     |Eeschema                                |回路図エディタ                |
schematic library editor     |コンポーネント・ライブラリ・エディタ    |                              |
CvPcb                        |CvPcb                                   |フットプリント・セレクタ      |
Pcbnew                       |Pcbnew                                  |プリント基板エディタ          |
PCB footprint editor         |PCB フットプリント・エディタ            |                              |
GerbView                     |GerbView                                |ガーバー・ビューア            |
Bitmap2Component             |Bitmap2Component                        |                              |
PCB Calcurator               |PCB 計算機                              |                              |
PL Editor                    |図枠エディタ                            |                              |
IDF Exporter                 |IDF Exporter                            |                              |

できるだけ、固有名称があるものは、Eeschema や Pcbnew のように表記した方が分かり易いと思います。
ただ、コンポーネント・ライブラリ・エディタとPCBフットプリント・エディタは固有名称がないので、
明確に決めてしまいたいなと思いました。

よろしければ、GUIの既存のモノもこれに合わせていきたいと考えてます。
またマニュアルの方もこれに合わせていきたいです。
いかがでしょうか？
別の訳語が良いというのも含めましてご意見よろしくお願いします。

**Comment by starfort-jp** [comment]
独立したツールの固有名詞は変更しない方がいいと思います。（日本語化しない）
理由は一般名詞化すると混乱を招くからです。（上の例で言うと回路図エディタ、図枠エディタなど）
独立していないツールは起動時のタイトルバーの名称を使うで統一してはどうでしょうか？
原版でも表記ゆれがあり混乱の元凶ですが、一般にソフト名はタイトルバーやAboutパネルに出すものと認識しています。

**Comment by kinichiro** [comment]
@starfort-jp さん、同意します。私も一般名詞化はしたくないと思ってました。
コンポーネント・ライブラリ・エディタとPCBフットプリント・エディタを表記上
固定したいなと考えてのことです。
一部表を修正しました。

英語                         |翻訳での表記                            |日本語説明                    |
-----------------------------|----------------------------------------|------------------------------|
KiCad                        |KiCad プロジェクト・マネージャ          |                              |
Eeschema                     |Eeschema                                |回路図エディタ                |
schematic library editor     |コンポーネント・ライブラリ・エディタ    |                              |
CvPcb                        |CvPcb                                   |フットプリント・セレクタ      |
Pcbnew                       |Pcbnew                                  |プリント基板エディタ          |
PCB footprint editor         |PCB フットプリント・エディタ            |                              |
GerbView                     |GerbView                                |ガーバー・ビューア            |
Bitmap2Component             |Bitmap2Component                        |                              |
PCB Calcurator               |PCB Calcurator ~~PCB 計算機~~           |                              |
PL Editor                    |PL_Editor ~~図枠エディタ~~              |図枠エディタ                  |
IDF Exporter                 |IDF Exporter                            |                              |

**Comment by starfort-jp** [comment]
PCB フットプリント・エディタが悩ましいですね。自分で使っておいて何ですが(*^.^*)ゞ、ソフトのタイトルバーは フットプリント・エディタになってます。こちらに統一しては如何でしょう？

**Comment by kinichiro** [comment]
起動時のタイトルバーの名称でまとめ直してみました。
Bitmap2Component は起動してみたら以下のようになってますが、
一般的な言葉になってしまうので、KiCad画面のボタンのツールチップにある
Bitmap2Component で表記としました。（難しいですね、表記が揺れていて。。。）

起動時のタイトルバーの名称   |翻訳での表記                            |日本語説明                    |
-----------------------------|----------------------------------------|------------------------------|
KiCad                        |KiCad                                   |プロジェクト・マネージャ      |
Eeschema                     |Eeschema                                |回路図エディタ                |
Part Library editor          |コンポーネント・ライブラリ・エディタ    |                              |
Cvpcb                        |Cvpcb                                   |フットプリント・セレクタ      |
Pcbnew                       |Pcbnew                                  |プリント基板エディタ          |
Footprint Editor             |フットプリント・エディタ                |                              |
GerbView                     |GerbView                                |ガーバー・ビューア            |
Bitmap to Component Converter|Bitmap2Component                        |                              |
PCB Calcurator               |PCB Calcurator                          |                              |
Pl_Editor                    |Pl_Editor                               |図枠エディタ                  |
(IDF Exporter はなし)        |IDF Exporter                            |                              |


この表に基づいて、画面上の表記を以下のように変更を、と考えてます。
- KiCad 画面の各ボタンのツールチップ
  - 回路図ライブラリエディタ → コンポーネントライブラリエディタ
  - PCBフットプリントエディタ → フットプリントエディタ
  - 図枠エディタの起動 → 図枠エディタ(Pl_Editor)の起動
- KiCad 画面の「ツール」メニューの各名称
  - ライブラリエディタの起動 → コンポーネントライブラリエディタの起動
- Eeschema 画面のトップツールバーのツールチップ
  - ライブラリ・エディタ → コンポーネント ライブラリ エディタ
- Eeschema 画面の「ツール」メニューの名称
  - ライブラリ・エディタ → コンポーネント ライブラリ エディタ

Getting Started in KiCad も、回路図ライブラリエディタにしてしまってますが、
置換で直せますので画面に合わせて対応することを考えてます。

**Comment by kinichiro** [comment]
画面上のコンポーネントライブラリエディタとフットプリントエディタの表示の件、
PR出させてもらいました。 
https://github.com/kicad-jp/kicad-gui/pull/2

**Comment by starfort-jp** [comment]
PcbnewのPCB フットプリント・エディタをフットプリント・エディタへ置き換えました。(07/21/2015)
もう少し見直してから、米倉さんへお送りします。

**Comment by kinichiro** [comment]
@yoneken さん、１つ御知らせです。
http://bazaar.launchpad.net/~kicad-developers/kicad/doc/files/head:/internat/ja/ を見ると、
kicad.mo が kicad.po より古い日付になっています。
これが理由で、最新のビルドでも一つ古い内容のkicad.moが読み込まれてます。

**Comment by yoneken** [comment]
@kinichiro おっと？！
了解です！！お知らせ，ありがとうございます♪

**Comment by kinichiro** [comment]
@yoneken さん、ご対応ありがとうございます。
変更した内容がGUIで反映されているのを確認できました！

**Comment by yoneken** [comment]
This issue was moved to kicad-jp/kicad-i18n#1
