### ISSUE TITLE
ホットキーの一覧の日本語化

### ISSUE THREAD

**Issue by kinichiro** [kicad-jp/kicad-gui#3]
現時点で @starfort-jp さんがほとんど日本語化して下さってて、
メニュー、アイコンのツールチップ、コンテキストメニュー、ダイアログ、等々、
ほぼ全て日本語化が完了してる状態ですが、**? キー** で表示される
ホットキーの一覧にはまだ日本語化されていない説明文があります。

この辺りを多少直そうかと思ったのですが、そもそも kicad.po ファイルに
ホットキーの説明文が落ちてないようです。

これはおそらくプログラムのソースコード側が多言語化対応してないからなのでしょうね？

**Comment by yoneken** [comment]
This issue was moved to kicad-jp/kicad-i18n#2
